### ISSUE TITLE
Starting >>> console_bridge_vendor --- stderr: console_bridge_vendor

### ISSUE THREAD

**Issue by sicklememe** [m2-farzan/ros2-galactic-PKGBUILD#31]
Sorry to bother you.but I don't know how to solve this problem.
```
Starting >>> console_bridge_vendor
--- stderr: console_bridge_vendor
CMake Error at /tmp/makepkg/ros2-galactic/src/install/share/performance_test_fixture/cmake/ament_cmake_export_targets-extras.cmake:18 (message):
  Failed to find exported target names in
  '/tmp/makepkg/ros2-galactic/src/install/share/performance_test_fixture/cmake/performance_test_fixtureExport.cmake'
Call Stack (most recent call first):
  /tmp/makepkg/ros2-galactic/src/install/share/performance_test_fixture/cmake/performance_test_fixtureConfig.cmake:41 (include)
  /tmp/makepkg/ros2-galactic/src/install/share/ament_lint_auto/cmake/ament_lint_auto_find_test_dependencies.cmake:36 (find_package)
  CMakeLists.txt:104 (ament_lint_auto_find_test_dependencies)


---
Failed   <<< console_bridge_vendor [1.14s, exited with code 1]

Summary: 108 packages finished [6min 23s]
  1 package failed: console_bridge_vendor
  44 packages had stderr output: ament_clang_format ament_clang_tidy ament_copyright ament_cppcheck ament_cpplint ament_flake8 ament_index_python ament_lint ament_lint_cmake ament_mypy ament_package ament_pclint ament_pep257 ament_pycodestyle ament_pyflakes ament_uncrustify ament_xmllint console_bridge_vendor cyclonedds domain_coordinator fastrtps foonathan_memory_vendor google_benchmark_vendor iceoryx_posh launch launch_testing launch_xml launch_yaml mimick_vendor osrf_pycommon osrf_testing_tools_cpp performance_test_fixture pybind11_vendor rosidl_cli rpyutils rti_connext_dds_cmake_module rviz_ogre_vendor shared_queues_vendor spdlog_vendor test_osrf_testing_tools_cpp tracetools_read tracetools_trace uncrustify_vendor urdfdom_headers
  221 packages not processed
```

**Comment by jjcindy115** [comment]
Same error after applying the " python-pyqt5 dropped sip4-support patch #9 "

**Comment by jjcindy115** [comment]
**Error log after applying the python-pyqt5 dropped sip4-support patch**

Failed   <<< console_bridge_vendor [2.56s, exited with code 1]

Summary: 113 packages finished [56min 52s]
  1 package failed: console_bridge_vendor
  46 packages had stderr output: ament_clang_format ament_clang_tidy ament_copyright ament_cppcheck ament_cpplint ament_flake8 ament_index_python ament_lint ament_lint_cmake ament_mypy ament_package ament_pclint ament_pep257 ament_pycodestyle ament_pyflakes ament_uncrustify ament_xmllint console_bridge_vendor domain_coordinator fastrtps foonathan_memory_vendor google_benchmark_vendor iceoryx_posh ignition_cmake2_vendor ignition_math6_vendor launch launch_pytest launch_testing launch_xml launch_yaml mimick_vendor osrf_pycommon osrf_testing_tools_cpp performance_test_fixture pybind11_vendor rosidl_cli rpyutils rti_connext_dds_cmake_module rviz_ogre_vendor shared_queues_vendor spdlog_vendor test_osrf_testing_tools_cpp tracetools_read tracetools_trace uncrustify_vendor yaml_cpp_vendor
  226 packages not processed
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'ros2-humble-2022.05.23-1': 
error: packages failed to build: ros2-humble-2022.05.23-1

**Comment by m2-farzan** [comment]
Thanks for reporting the issue. I just ran the tests and verified [the error is reproducible](https://github.com/m2-farzan/ros2-galactic-PKGBUILD/runs/7894994231?check_suite_focus=true). I will update the package as soon as I find out what causes the issue, but I'm afraid I'm too busy this week, so a PR is much appreciated as well.

**Comment by m2-farzan** [comment]
The issue is fixed now. Thanks again, @luoiohub for bringing this to attention.
