### ISSUE TITLE
Remove calls to sudo from PKGBUILD

### ISSUE THREAD

**Issue by rmsc** [m2-farzan/ros2-galactic-PKGBUILD#6]
I think there are cleaner ways to install the sip symlinks than calling `sudo` inside the `PKGBUILD`.

One possibility that comes to mind is installing them with a 'compatibility' package.

**Comment by m2-farzan** [comment]
A little bit of concurrency right there :)

**Comment by m2-farzan** [comment]
Thanks for your contribution!
